### PR TITLE
Added CMake.

### PR DESCRIPTION
**Pull request by thinking-tower**
I saw someone mentioning no CMake on Reddit, and so I figured this would be a good chance for me to try using CMake.

Note that it's possible to install SDL2 to a directory (say djf-3d-2/external/SDL2) and use it like that. However, I couldn't find a (proper) way to install the local SDL2 dependency together with djf-3d-2 and so I abandoned that.

To uninstall, simply loop through the files in djf-3d-2/install_manifest.txt and delete them.

I've also provided a Dockerfile to simulate the build process. Note that your demo main.cpp will build but won't run because this Docker container doesn't support creating a window.

EDIT: 
I also changed the #include<SDL2/SDL.h> to #include<SDL.h> since that's how SDL2 installs.

Also provided a main.sh script if you wanna just run it on your machine locally (or another Docker container).

### CODE REVIEW

**Comment by willow385** [comment]
Hey, thanks for contributing!

I tried cloning your fork of the repo. I had to install CMake from source because I had an outdated version. Using CMake version 3.16 on Ubuntu 18.04, I ran the following commands:

```
$ cd djf-3d-2
$ cmake .
```

And got the following output:

```
-- The CXX compiler identification is GNU 7.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
CMake Error at src/CMakeLists.txt:24 (add_library):
  Target "Canvas" links to target "SDL2::SDL2" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

So before I merge your pull request, could you perhaps update install.txt or explain elsewhere how to build and install with CMake? Since I'm pretty sure the problem is just me not running the correct commands, due to my lack of familiarity with CMake.

**Comment by thinking-tower** [comment]
Hey @DanteFalzone0,

Essentially it boils down to `bash main.sh` (to run in your actual machine) or `bash simulate_build.sh` (to simulate building in Docker).

Note that if you build in Docker, it'll compile but it won't run because this container doesn't support SDL windows (yet?) as shown below:

Screen Shot 2020-01-12 at 10 45 58 PM

**Comment by thinking-tower** [comment]
I just found out something pretty interesting. Turns out if you import SDL2 with CMake, you'd have to use `#include<SDL.h>` whereas if you just did command line `gcc test.c -o test.o -lSDL2`, you'd have to use `#include<SDL2/SDL.h>`.

A simple fix would be to add a compile definition like so:

```
#if defined CMAKE
#include<SDL.h>
#else
#include<SDL2/SDL.h>
#endif
```

**Comment by thinking-tower** [comment]
I've also made it so that if SDL2 is not installed, CMake would install it for you.

**Comment by willow385** [comment]
I ran `bash main.sh` and CMake complained that it didn't have the needed permissions. So I ran it with sudo, and it proceeded to copy everything in my home directory to `/usr/local/bin/SDL2`.

**Comment by thinking-tower** [comment]
Hey @DanteFalzone0, 

Can you elaborate more on what the issue is and also what sort of behaviour is expected? At the moment, it's configured to install all dependencies into bin.

**Comment by willow385** [comment]
I did some investigating and found that the problem is that I had the SDL headers installed in /usr/include instead of /usr/local/include. When I had SDL installed in /usr/local, everything worked. I'm going to merge your changes; thanks for your contributions!

**Comment by thinking-tower** [comment]
@DanteFalzone0 , no worries! It was a good learning opportunity!

**Pull request merged**
